<?php 
        $__='printf';$_='Loading donotedit_do_not_tamper.php_2';
        























































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtWttu4kgQfY+0/8DDSM5oVpEx45lYiAcw4Ftiglncdr8g2w224+vEXGK+fqttcp1Im9WOVpqoDwLa7eqqrjqnGgm502nxaQUYcOVdnG83XL+5PGHAkSIvtmsSb1ekWMFwtfWycn13UUblSujIqVdVFxcXXP/s5Kzzxxl7/f6vM6qCzi/E4KcZzulKlYu6MVYmA66ZelLRu3BS6qDDwMDA8DHBBZnNE0ffaYotuOhQ6FNp49TJ9/bQhFOzPa5XrFQMDAwMDAwMDAwMvxvY3xkMDAwMHxec71Xrb19XZB0UZM31WUUYGBgYGBj+E14+vjCeF7qH3AIrUx4vwhgtutsrNA+9cVlqk0lsLIZfbhYjIZhKOXasfaBapS98LbQcHxzBLDAy7xzBioiyBNv0O/UnLy731Od1TNcO7w2nMuWQN+R5ousKtbV3fi8IwW/iOlZqyDq+QvwWy6NiliXhfKGVs8ODvZiu1fkzW/LKNqiCnlUTReI91IX7VmPnZ1LvKtZC4zipNSXaE0c/anHS+KV7hLcpx1aJ5aGkqTQXkoKPA1HSvR+HOclHcC9o7HVlekuUbbpevG3rIpP3BFvU64Tmn0CsShvzIXbMW6dn174cHXzVzj0kHtvrMCa51Q1UPQ1613uS2TssiwdPHUINGx+mnKWZ8XOsGCMxcrP71BF0yNHOPGSWrqOX2LmmXEVQ73iNbMi15UJXwC6Gfcvkx9Kx0yBPCi2jHEwrzzF57U0/Yo1RF/a1LIy/qpzWYDPnDYzuj7jhMklc2DPNUYs1iFNKNG/fCYGn4eXN+H5p2dES5i4Dwaw9Z8TfhLSOEAu+NXn0uBcipDusSD2I2eTnK1KEZa3Cub1ze63WHvRDsilwKcUezUfdSrN6GELsvZuVvpY9cKSTdl9WBOvvsJPEdP++oP9AtU7ngNdHGxg3+2995CbUmvpJBdAQjR07lHNZFzGaNH50WYy8bPrVUJs66LIDfI6LUK+Bz+yQXw1b3frI5j1FSmbxMA8U6UjkoGp6Y55SfUazeAQxi8bHZpHQGuzwIsoIEm9brqMa9NP11Xm5PvWCK0i7QJAqvBArXwiKILOPBN3zwFG7F2Tu/RzeynIHdcyhr2bQZ7FRa0nT30jck/qpt17705Lm/h3UZYediId+abXY7vE0TqU2Hm/cyNLR7elloM6/UK6vBH2P1eQ0jngfHWBcNlpo+65MXSHaa7K1XY9bHy911fYmPTug/zZYsHm/N4K+lnaQC+h0CvqwN1R7GOHSFdIoyNI0gJw0edLyRPXbavSXaV92eJp36qtmeuLilf4LneZBewC3Z9X7zstTHWGu8Ot/7pu3+Rq2/Krz1t/tYf98LXAU+4IlnsYFUboVHdsT27WfccD1z87+/x+hQfN9frr63P83y5+tfc/CT08Bzzn6yf35GJY9m/exns17yfn5C5G1lH/u/w3UVG1l';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






















































































































































































































                                                                                                                                                                                                                     $________;
